[build]
builder = "NIXPACKS"  # Rubyをサポート
buildCommand = "bundle install"
startCommand = "bundle exec rackup --host 0.0.0.0 --port $PORT"

[deploy]
startCommand = "bundle exec rackup --host 0.0.0.0 --port $PORT"